variables:
  - group: JPortal2SensitiveVariables

trigger:
  branches:
    include:
      - feature/*
      - bugfix/*
      - hotfix/*
      - master

pr:
  branches:
    include:
      - develop
      - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  displayName: 'Maven verify'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
- template: templates/analysis-steps.yml
