trigger:
  branches:
    include:
      - 'refs/tags/*'
jobs:
- job: publish_release
  displayName: Build and Publish Release
  variables:
    - group: JPortal2SensitiveVariables
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) 
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - checkout: self
    persistCredentials: true
  - template: templates/maven.yml
  - template: templates/analyse.yml
  - bash: |
      extracted_version=$(echo "$BUILD_SOURCEBRANCH" | rev | cut -d/ -f1 | rev)
      echo "##vso[task.setvariable variable=project_version]$extracted_version"
    displayName: 'Extract version from Git tag'
    failOnStderr: true  
  - template: templates/download-secure-files.yml
  - template: templates/maven.yml
    parameters:
      displayName: 'Maven deploy release version'
      goals: | 
        --settings=$(mavenSettings.secureFilePath) -Pcreate-release-version,release-oss-maven-central  -DreleaseVersion=$(project_version)-RELEASE -Dgpg.publicKeyring=$(publicKeyRing.secureFilePath) -Dgpg.secretKeyring=$(privateKeyRing.secureFilePath) deploy
  # 4. Create github release