variables:
  - group: JPortal2SensitiveVariables
condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/')) 
trigger:
  branches:
    include:
      - 'refs/tags/*'
pool:
  vmImage: 'Ubuntu-16.04'
steps:
# 1. Get version from tag name
# 2. Update pom version with maven
# 3. run mvn deploy
# 4. Create github release
- task: Maven@3
  displayName: 'Maven deploy release'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
- template: templates/analysis-steps.yml
