variables:
  - group: JPortal2SensitiveVariables

trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# 1. Update pom version with maven to current CICD version
# 2. mvn deploy
- task: Maven@3
  displayName: 'Maven deploy snapshot'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
- template: templates/analysis-steps.yml
