variables:
  - group: JPortal2SensitiveVariables

trigger:
  branches:
    include:
      - develop

pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
- task: Maven@3
  displayName: 'Maven deploy snapshot'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean deploy -Pincrement-minor-version,release-oss-maven-central'
- template: templates/analysis-steps.yml #Might want to check status of this step
- template: templates/extract-version.yml
- bash: |
    git add 'pom.xml'
    git commit -m "CICD: Minor version bump - ${project_version}"
    # have to push changes here
  displayName: 'Git commit POM updates'
  failOnStderr: true  
